name: CI
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java: [openjdk@1.8, openjdk@1.11]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v6
        with:
          java-version: ${{ matrix.java }}
      - run: git fetch --tags
      - run:
          # for GitOps tests	
          git config --global user.email "scalafmt@scalameta.org" && git config --global user.name "scalafmt"
      - run: TEST="2.11" sbt ci-test
      - run: TEST="2.12" sbt ci-test
      - run: TEST="2.13" sbt ci-test
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v6
      - run: ./scalafmt --test
      - run: yarn install
      - run: yarn format-check
  native-image:
    runs-on: ${{ matrix.os }}
    env: 
      GRAALVM_VERSION: 20.1.0
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, ubuntu-latest]
        include:
          - os: macOS-latest
            artifact: scalafmt-macos
            config: macos
          - os: ubuntu-latest
            artifact: scalafmt-linux-glibc
            config: linux-glibc
          - os: ubuntu-latest
            musl: https://github.com/gradinac/musl-bundle-example/releases/download/v1.0/musl.tar.gz
            artifact: scalafmt-linux-musl
            config: linux-musl 
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: graalvm-ce-java11@20.1.0
      - if: matrix.musl != null
        run: |
          wget ${{ matrix.musl }}
          tar xvf musl.tar.gz
          echo ${PWD}

      - run: bin/build-native-image.sh
        env:
          CI: true
          NATIVEIMAGE_CONFIG: ${{ matrix.config }}
      - uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.artifact }}
          path: scalafmt
